### ISSUE TITLE
Integrate Firebase? database 

### ISSUE THREAD

**Issue by Rafna** [women-who-software/returnship-everydayheroes#14]
- store the values entered into the form

This is an enchantment feature if Micheal gets more than 100 submissions per month.

**Comment by domsbytes** [comment]
Right now the entered form details are posted and stored in the netlify dashboard. We can set up a hook to send an email to Micheal/ podcast every time someone enters information into the form. He can then set up a filter in the email to gather all the submission emails in a folder where its a bit more organized. 

This is a free feature provided by netlify. Up to 100 form submissions a month. 

- Recommending this for the time being as it saves time with an implementation of a database and setup.

**Comment by Rafna** [comment]
Yeah, that works for the initial stage. We will keep this in the review till we discuss in the next meeting.

**Comment by domsbytes** [comment]
We decided not to integrate a database.
