### ISSUE TITLE
Landing page mockup

### ISSUE THREAD

**Issue by ChetanaPatil217** [women-who-software/returnship-everydayheroes#2]
Create a wireframe/mockup for the landing page. 
So ideas for the landing page would be: 
1. Welcome statement for this page
2. Summary of what this website is about
3. What prompted them to do build this website
4.  What is the goal of this website
5. Link to the next action such as submit form, index page, etc.

**Comment by cssteffen** [comment]
Mock-up Idea for landing page.
<img width="635" alt="Screen Shot 2020-05-26 at 11 27 05 AM" src="https://user-images.githubusercontent.com/30050423/82931261-de559f80-9f43-11ea-8354-7d53daf1f781.png">

https://xd.adobe.com/view/e06e3dd9-6f66-427f-6bb9-fc64e664efa4-965f/

**Comment by Rafna** [comment]
Closing this issue as the layout is approved by client
