### ISSUE TITLE
design and add a custom favicon

### ISSUE THREAD

**Issue by domsbytes** [women-who-software/returnship-everydayheroes#21]
Currently, we have a Gatsby Favicon showing up in our site :) so we just need to replace it with our custom one. 

guide: https://medium.com/@itguymax/add-a-custom-icon-to-your-gatsby-site-in-just-a-few-a-minute-4e5b5f12ca40

**Comment by cssteffen** [comment]
created icon.png for favicon and put in image/src folder. 
Pushed changed to git // new favicon is live
