### ISSUE TITLE
Index page mockup

### ISSUE THREAD

**Issue by ChetanaPatil217** [women-who-software/returnship-everydayheroes#3]
Create a wireframe/mockup for the index page to list all the podcasts
Some of the ideas for this is:
1. A grid view list 
2. A tile view list
3. 10 items per page
4. Scrolling feature to load next 10 items
5. Link to share on social media
6. Link to submit form page
7. Play button to watch/listen podcast
8. May be a link to details page of the selected podcast

**Comment by cssteffen** [comment]
Created a wireframe design for the podcast index page.

https://xd.adobe.com/view/e06e3dd9-6f66-427f-6bb9-fc64e664efa4-965f/

<img width="490" alt="Screen Shot 2020-05-26 at 6 15 09 PM" src="https://user-images.githubusercontent.com/30050423/82962243-e7af2e00-9f7c-11ea-907e-e4ae5c31a045.png">

**Comment by Rafna** [comment]
Will be discussing on this layout and other details in the next team meeting
