### ISSUE TITLE
Submission form page mockup

### ISSUE THREAD

**Issue by ChetanaPatil217** [women-who-software/returnship-everydayheroes#4]
Create a wireframe/mockup for users to submit a form

1. Sample form to collect stories:
    Full Name:
    Email Address:
Physical Address:
Phone Number:
Are you willing to share your story using Zoom?
Are you willing to let someone else share your story using Zoom?
Give a short summary of your story.
Tell us your story, providing as much detail as you want.
Do you have any questions for us?

2. Option to save, cancel and submit

3. On submit send notification email to User and Admin.

**Comment by cssteffen** [comment]
Let me know your thoughts on simplifying the submission form. 
I thought it might be best to keep the form on the landing page so the user stays engaged and sees how simple it is to submit a story.
  
I was thinking on the drop down menu-item of "Are you willing to share your story over Zoom?" That we could have options of "Yes", "No", "I'd like someone else to share my story"

<img width="214" alt="Screen Shot 2020-05-26 at 11 31 09 AM" src="https://user-images.githubusercontent.com/30050423/82931766-a8fd8180-9f44-11ea-8969-67be9831253d.png">

**Comment by cssteffen** [comment]
We could have the "Invite others to share" with social media links on the "Thank you Feedback page" once a story has been submitted.

**Comment by Rafna** [comment]
Submission form layout is approved by client, closing this issue
